from .content_similarity import extract_website_content, extract_website_content_using_selenium, clean_text, remove_stop_words, calculate_similarity
from .determine_status import determine_status
from .domain_similarity import strip_tld, remove_substrings, calculate_domain_similarity
from .ensure_scheme import ensure_scheme
from .malicious_ip import read_malicious_ips_from_csv, get_ip_address, get_ip_addresses, check_if_malicious
from .redirecting import get_domain_from_url, fetch_urls_and_check_redirect
from .title_similarity import get_title, compare_titles
from .save_results_to_csv import save_results_to_csv
from .fetch_domain_data import fetch_domain_data
from .get_next_available_filename import get_next_available_filename
from .process_child_domain_in_batches import process_child_domains_in_batches
from ..config import content_cache, title_cache, url_queue